baseURL = "https://frenel.jp/"
languageCode = "en-us"
title = "合同会社フレネル（Frenel, LLC.）公式サイト"

ignoreFiles = [ "\\.scss$"]

[Params]
  stylesheet = "css/style.css"
  description = "フレネルは、九州アジアを拠点とするクリエイターのエージェント、Webディレクション、地域デザインなどを行う企業です。皆さんのはじまりを、あと押しします。"
  analytics = ""

[Social]
  twitter = ""

[permalinks]

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"
